apiVersion: v1
kind: Service
metadata:
  labels:
    app: assessment-service
    tiers: frontend
  name: assessment-service
spec:
  ports:
  - name: http
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: assessment-service
    tiers: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: assessment-service
        tiers: frontend
    spec:
      containers:
      - image: rajeevmitra/assessment-service
        name: assessment-service
        ports:
        - containerPort: 8444
          name: http
status: {}