FROM openjdk:8-jdk-alpine
LABEL maintainer="rajeev mitra"
EXPOSE 8444
VOLUME /tmp
ADD target/rest-service-0.0.1-SNAPSHOT.jar rest-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","rest-service-0.0.1-SNAPSHOT.jar"]