apiVersion: v1
kind: Service
metadata:
  labels:
    app: project-service
  name: project-service
spec:
  ports:
  - name: http
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: project-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: project-service
        tiers: frontend
    spec:
      containers:
      - image: <image repository >
        name: project-service
        ports:
        - containerPort: 8444
          name: http
        env: 
        - name: SEARCH_SERVICE_URL
          value: <url>
status: {}